
name: Cert Tracker CI with Maven

on:
  push:
    branches: [ "main","develop" ]
    
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: devop
          MYSQL_DATABASE: certificatetracke
          MYSQL_USER: devop
          MYSQL_PASSWORD: devop
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 3306:3306
    permissions:
      id-token: write
      contents: read
      checks: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Wait for MySQL to start
      run: |
        for i in {1..30}; do
          mysql -h 127.0.0.1 -P 3306 -u root -pdevop -e "SELECT 1" && break || sleep 10
        done
    - name: Build with Maven
      run: mvn clean verify 

    - name: Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Spring Boot Tests
        path: target/surefire-reports/*.xml
        reporter: java-junit
        fail-on-error: true
    
    
    

